files:
    filename: Portfolio
    data_file: E:\Self\data.csv 

paths:
    dl_path: C:\Users\John\Downloads\Portfolio.xls
    dest_path: E:\Self\data
    save_path: E:\Self\wykresiki

pass:
    sender: Grappa2021